### PR TITLE
Fixes mv

### LINKED ISSUE #45: fix mv

### PR DESCRIPTION
**Pull request by rossem**
Mv now works

closes #45

### CODE REVIEW

File: rules/mv.go [hunk 1]
```diff
@@ -17,8 +20,27 @@ func isMatchMv(cmd models.Command) bool {
...
+	var oldFromTokens = strings.Split(oldFrom, "/")
+	var oldToTokens = strings.Split(oldTo, "/")
+
+	wasRenamed, err := utils.WasRenamed(oldFromTokens, oldToTokens)
+	if err != nil {
+		return "", err
+	}
+
+	if !wasRenamed {
+		oldToTokens = append(oldToTokens, oldFromTokens[len(oldFromTokens)-1])
```
Comment (Wojtechnology) [inline rules/mv.go]: Could create var for `len(oldFromTokens)`.
